### ISSUE TITLE
Importing post-robot

### ISSUE THREAD

**Issue by vovimayhem** [krakenjs/post-robot#29]
Hi! I'm having a bit of trouble with importing post-robot inside an Ember component. I strongly suspect this is something easy:

```javascript
import Ember  from 'ember';
import postRobot from 'post-robot';
```

This will fail with the following message:

```
Error: Could not find module `post-robot` imported from (...)
```

How I'm supposed to refer to postRobot from here?? I added it to my project with `npm install --save post-robot`...

**Comment by vovimayhem** [comment]
Got it working!

To make the library accessible via import, I generated an "ES6 shim". See the ["Managing Dependencies - Standard Non-AMD Asset"](https://ember-cli.com/user-guide/#standard-non-amd-asset) section in the Ember CLI guides.

**Comment by bluepnume** [comment]
Weird. post-robot should be AMD-ified already by webpack. Going to re-open this so I can look into it.

**Comment by bluepnume** [comment]
Yeah, tried this for myself and it seems like there's not much that can be done in post-robot to avoid needing that ES6 shim to be generated. Shame, since tools like webpack manage just fine. Any ember-cli experts ever read this and know a better way of solving this for everyone, please let me know.
