### ISSUE TITLE
Supporting subdomains

### ISSUE THREAD

**Issue by cyanCYMK** [krakenjs/post-robot#43]
I'm proposing a feature idea for post-robot to accept messages from top-level domains like `postRobot.send(someWindow, "messageType", data, { domain: "*.domain.com" });`

Thoughts?

**Comment by bluepnume** [comment]
You can already pass a regex as the domain. Does this work for your use case?

**Comment by cyanCYMK** [comment]
I can see that `matchDomain` will check for regex. I'm having trouble figuring out how I can use regex. I'm using it like `postRobot.send(someWindow, "messageType", data, { domain: /myregex/g });` and `getDomain` doesn't seem to check for regex. Am I missing something?

**Comment by bluepnume** [comment]
Ohh, hang on -- yeah, I see the problem. You can specify a regex in a listener, but not when you're sending a message.

The problem is, `window.postMessage(message, domain)` only lets you specify a string as the domain.

Thinking about it... we could send a preflight message to verify the domain before sending the actual message. But this would be a little slower. I'll keep this open and think if there's a better way.

**Comment by bluepnume** [comment]
We ended up using the preflight method. So you can now use a regex in send().
